### ISSUE TITLE
Unable to run it in the local

### ISSUE THREAD

**Issue by NaveenThally** [karify/external-svg-sprite-loader#46]
@bensampaio 

**Getting error as below** 

_`module.js:549
    throw err;
    ^

Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Library/WebServer/Documents/external-svg-sprite-loader/lib/SvgStorePlugin.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`_

am i missing something. i couldn't find Chunk in my webpack installation in node_modules

**Comment by bensampaio** [comment]
Which version of webpack and of this plugin are you using?

**Comment by NaveenThally** [comment]
i'm using the latest one webpack - 4.5.0 , external-svg-sprite-loader - 4.0.0-beta.4

**Comment by bensampaio** [comment]
The  file is still there: https://github.com/webpack/webpack/blob/v4.5.0/lib/Chunk.js. I guess there is something wrong with your `node_modules` folder. Have you tried to remove the folder and install again?

**Comment by bensampaio** [comment]
Closing because of no activity. Comment again to reopen or start a new issue if the problem persists.
